title: Herbal Indulgence
description: Home of High-Risk Processing - Next-gen POS for cannabis dispensaries & growers.
baseurl: "/herbalindulgence-site"  # Add thisâ€”fixes paths for project repo
url: "https://mcdpayzero.github.io"  # Your GitHub username
paginate: 5

# SEO & Plugins
permalink: pretty
exclude: [Gemfile*, README.md]
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Disable fallback theme
theme: null

# Design Vars
colors:
  green: '#228B22'
  gold: '#DAA520'
  neutral: '#F5F5F5'
